name: Build

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Configure Git User Details
        run: git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"
      - name: Get project version
        id: project-version
        run: echo "::set-output name=VERSION::$(./gradlew -q printVersion)"
      - name: Apply Patches
        run: ./gradlew clean build
      - name: upload
        uses: actions/upload-artifact@v4
        with:
         name: HuskSync
         path: target/*.jar
      - name: automatic releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
         repo_token: "${{ secrets.GITHUB_TOKEN }}"
         automatic_release_tag: "linux-latest"
         prerelease: false
         title: "HuskSync ${{ steps.project-version.outputs.VERSION }} 构建版本"
         files: |
           target/*.jar
  runtime-test:
    name: Plugin Runtime Test 
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - mcVersion: '1.8.8'
            javaVersion: '8'
          - mcVersion: '1.12.2'
            javaVersion: '8'
          - mcVersion: '1.20.2'
            javaVersion: '20'   
    steps:        
      - uses: HaHaWTH/minecraft-plugin-runtime-test@paper
        with:
          server-version: ${{ matrix.mcVersion }}
          java-version: ${{ matrix.javaVersion }}
          artifact-name: HuskSync
