# Builds, tests the project with Gradle
name: CI Tests

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Configure Git User Details
        run: git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"
        
      # 第一次构建
      - name: build
        id: build_1
        run: ./gradlew build
      # 第二次构建
      - name: build (retry 1)
        id: build_2
        if: steps.build_1.outcome == 'failure'
        run: ./gradlew build
       # 第三次构建
      - name: build (retry 2)
        id: build_3
        if: steps.build_2.outcome == 'failure'
        run: ./gradlew build
       # 第四次构建
      - name: build (retry 3)
        id: build_4
        if: steps.build_3.outcome == 'failure'
        run: ./gradlew build
        
      - name: Tasks
        run: ./gradlew tasks
      - name: Find And Rename
        run:  |
             cd target/
             mv HuskSync-Bukkit-*.jar HuskSync.jar
             mv HuskSync-Plugin-*.jar HuskSync-Plugin.jar
      - name: upload
        uses: actions/upload-artifact@v3
        with:
         name: HuskSync
         path:  |
              target/HuskSync.jar
              target/HuskSync-Plugin.jar
